### ISSUE TITLE
Please add version numbers to the documentation.

### ISSUE THREAD

**Issue by hansgru** [telerik/kendo-docs#521]
Please add version numbers to the documentation.

A good example of this is Sencha:
http://docs.sencha.com/extjs/4.2.1/

As you can see, the user can very easily switch to a different version.

This is extremely important since projects are not updated all the time to the newest version.

regards.

**Comment by KirilNN** [comment]
Hi @hansgru,

We will consider adding functionality for adding different versions of the documentation. As soon as it is available, you will be able to see it live on docs.kendoui.com.

**Comment by hansgru** [comment]
@KirilNN so you close this issue, but haven't really fixed the problem yet :).

**Comment by KirilNN** [comment]
The issue is moved to https://github.com/telerik/kendo-ui-core/issues/636
