### ISSUE TITLE
Allow user comments on paragraphs in the online docs

### ISSUE THREAD

**Issue by hansgru** [telerik/kendo-docs#522]
Allow user comments on paragraphs in the online docs. So not comment threads on page, but simple comments on paragraphs. Also they should be collapsed by default.
The main purpose would be to increase the quality of the documentation by allowing the users to give feedback right away "in place" where things are not clear or not good enough.

Many other projects implemented this and it seems that the user contribution is very high in this case.

**Comment by underlog** [comment]
This will turn our documentation site into yet another support channel. Instead, we are considering adding convenience buttons for people to fork and edit the document they are currently on.

**Comment by hansgru** [comment]
> This will turn our documentation site into yet another support channel. 
@underlog As you could have red from my request, this is not for users to get support, but to give you inline feedback exactly at places where it's most needed: directly in the context.
