### ISSUE TITLE
Please add event lifecycle diagrams / explanations

### ISSUE THREAD

**Issue by advancedrei** [telerik/kendo-docs#562]
Currently, there is no documentation on for things like the order in which events are fired in the Grid control. It would be really helpful to be able to see how, for example, when you press the refresh button on the Grid, how Grid events bubble down to the DataSource and fire more events, then bubble back up to the Grid.

I'm just using the Grid as an example, but it really should happen for all components. Might even help ferret out places where you guys are missing events that should be fired (for example editStart and editEnd events).

**Comment by KirilNN** [comment]
Hi @advancedrei,

While it is a "nice to have" feature for our documentation, we currently do not have the resource to do a campaign on updating the event lifecycle for all the widgets. We will definitely consider this for a future implementation. And of course if you want to contribute to our documentation providing the event lifecycles - submit a pull request and we will be happy to accept it.
