### ISSUE TITLE
What is the recommended line length for .md files?

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#573]
This should be mentioned in the README / contributing instructions.

In one given file, I've seen it fluctuate wildly - [455 chars](https://github.com/telerik/kendo-docs/blob/master/api/javascript/ui/treelist.md#columnseditor-function) vs. [77](https://github.com/telerik/kendo-docs/blob/master/api/javascript/ui/treelist.md#pdfmargin-object).

**Comment by underlog** [comment]
We don't have any standard for the maximum line length, as long as it is readable. Nowadays most editors wrap long lines just fine.
