### ISSUE TITLE
When must the createChild command be capitalized?

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#576]
http://docs.telerik.com/kendo-ui/api/javascript/ui/treelist explains the `createChild` command, and follows it with many examples where it's lowercased to `createchild`. I'm not sure this is an error because `createchild` is sometimes used in [localizing messages](http://docs.telerik.com/kendo-ui/api/javascript/ui/treelist#configuration-messages), for example, and [`canceledit`](http://docs.telerik.com/kendo-ui/api/javascript/ui/treelist#configuration-messages.commands.canceledit) is similarly lowercased instead of `cancelEdit`. See also http://docs.telerik.com/kendo-ui/api/javascript/ui/treelist#configuration-messages.commands.createchild

The grid does camelCase multi-word `messages` properties **of the column configuration** - http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columnMenu.messages but not of commands - http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-messages.commands.

This looks like an inconsistency and it would be nice to have camelCase everywhere.

**Comment by KirilNN** [comment]
Moved to https://github.com/telerik/kendo-ui-core/issues/631
