### ISSUE TITLE
Mention how to create anchor links to subsections in the same doc

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#579]
https://github.com/telerik/kendo-docs/wiki/Topic-Sections should mention how to create anchor links, because this seems to differ from standard Markdown.

For example, in [the grid md](https://github.com/telerik/kendo-docs/blob/master/api/javascript/ui/grid.md) we have `[filterable](#configuration-filterable)`, while in normal Markdown, just `[filterable](#filterable)` should be enough. Should the section always prefix the subsection in the anchor name?

**Comment by underlog** [comment]
The change you refer to is introduced as a plugin in jekyll in the API reference. We need it because events and methods often have the same name.

**Comment by KirilNN** [comment]
The wiki is not updated explaining the convention for links to the different parts of the documentation.
