### ISSUE TITLE
Add an "edit" icon/button to docs.telerik.com

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#580]
It's [great](https://github.com/webix-hub/tracker/issues/177) that the documentation can be edited on GitHub, and it would be ever easier for users to see an "Edit this page" or "Contribute a correction" icon right on the page they're viewing. I'm surprising this isn't done already, as it could increase contributions by [a factor of 10](https://en.wikipedia.org/wiki/1%25_rule_(Internet_culture)).

Mongo does it - see the [pencil icon in the upper right corner](http://docs.mongodb.org/manual/reference/operator/update/inc/).

![image](https://cloud.githubusercontent.com/assets/33569/5585496/742014f0-9063-11e4-8440-3ce9003f09e2.png)

**Comment by gyoshev** [comment]
Very good idea, thanks!
