### ISSUE TITLE
Lots of less versions included in the download

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#593]
`telerik.kendoui.professional.2014.3.1119.trial.zip` includes in `src/build/less-js/dist` every less version from 1.1.6 to 1.6.0. Are the all necessary?

**Comment by underlog** [comment]
Yep. Not necessary. Fixed that. https://github.com/telerik/kendo-ui-core/commit/6b76122487e666bbb961dc7ee4105ff243ffbe87
