### ISSUE TITLE
Using <style scoped> is obsolete HTML5

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#601]
Many Kendo [demos](http://demos.telerik.com/kendo-ui/treeview/images) or examples use `<style scoped>`. However, [the `scoped` attribute is obsolete in HTML5](http://www.sitepoint.com/5-obsolete-features-html5/) and [support for it has been dropped in Chrome](https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/scoped/blink-dev/R1x18ZLS5qQ/Bjuh_cENhlQJ).

**Comment by gyoshev** [comment]
Thank you for the report, it has been addressed for future builds.
