### ISSUE TITLE
api/javascript/ui/treeview setDataSource / loadOnDemand

### ISSUE THREAD

**Issue by WarrenParks** [telerik/kendo-docs#635]
Rereading the documentation I guess it hints at this in the loadOnDemand section but I think it should be more clear especially on the setDataSource method... 

loadOnDemand will be set to false if you set the datasource to an array when you initialize the treeview however if you use the setDataSource method and pass it an array it does not follow this same behavior and you would need to set the loadOnDemand to false in the config.

**Comment by underlog** [comment]
Migrated to Migrated to core telerik/kendo-ui-core#629
