### ISSUE TITLE
Server grouping using kendo ui

### ISSUE THREAD

**Issue by samgreat99** [telerik/kendo-docs#638]
Hi.. Can anyone please provide some good demo to implement server grouping using kendo ui. My grid's data is bind through a web API call. I then want to add grouping on column names so that on select of a column data is again fetched through web API call.

**Comment by KirilNN** [comment]
Hi @samgreat99,

Thanks for your post, and for your interest in Kendo UI! **This issues list is for bugs only**, not help or support requests, so I’m going to close this issue with this comment.
