### ISSUE TITLE
Mismatch: `kendo.data.DataSource.filter` is function, not array or object

### ISSUE THREAD

**Issue by w1ld** [telerik/kendo-docs#641]
I'm using Kendo UI v2015.2.624 and Telerik ASP.NET MVC VSExtensions 2015.3.622.0 and it has `$("#myGridId").data("kendoGrid").dataSource.filter` equals to some `function(e){...}` that adds a filter to collection. 

But accordingly to [datasource doc](http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#configuration-filter) it should be either Array or Object. So the documentation does not match API.

The same for the latest Kendo UI Q2 2015 SP2 release. See [this Dojo](http://dojo.telerik.com/uJOqU).

PS. Yes, it returns the object if called as a function. Please see duplicate at Stackoverflow at http://stackoverflow.com/questions/32711005/mismatch-kendo-data-datasource-filter-is-function-not-array-or-object

**Comment by dimodi** [comment]
Hello w1ld,

`$("#myGridId").data("kendoGrid").dataSource.filter` points to the [`filter()`](http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#methods-filter) **method** of the Kendo UI DataSource, while the [linked documentation](http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#configuration-filter) specifies the valid arguments of the DataSource filter **configuration**.

**Comment by w1ld** [comment]
@dimodi Thanks! That misled me that as if configuration is the initialized object interface.
