### ISSUE TITLE
There is no `columns.filterable.operators` in the Grid's page in js api docs

### ISSUE THREAD

**Issue by germansokolov13** [telerik/kendo-docs#643]
I was looking for how to set up different filter operators for different columns in the Grid. Then I found the solution on Stackoverflow:
http://stackoverflow.com/questions/27226273/kendoui-grid-disable-some-filter-operators-per-column
But after I tried to check it out on this page in the docs:
http://docs.telerik.com/kendo-ui/api/javascript/ui/grid
there was no `columns.filterable.operators` in the Grid's configuration reference, only just `filterable.operators`.

Also another issue is that the docs say about `filterable.operators` that it just allows changing the message merely tweaking the appearance. But it appears, it actually allows completely changing the filters set up, which, I think, should be documented too.

**Comment by tsvetomir** [comment]
Moving this to telerik/kendo-ui-core#1335
