### ISSUE TITLE
FilterMultiCheck has no documentation in js api section

### ISSUE THREAD

**Issue by germansokolov13** [telerik/kendo-docs#644]
You can find this widget in the widget list in Kendo Ui chrome plugin tool. If you choose it and click the documentation button it takes you here:
http://docs.telerik.com/kendo-ui/api/javascript/ui/filtermulticheck
And the page is apparently non-existent (404)
This widget is created when grid's `columns.filterable.multi` option is used. It would be useful to know which public methods and events it might have if any.

**Comment by tsvetomir** [comment]
Transferring to telerik/kendo-ui-core#1334
